
env:
  global:
    - CC_TEST_REPORTER_ID=10ef165b8a27363c80f32fd188f6c23a2b675aaad2a91985e873cb3bc6ed25fc
language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: charlie@bowtie.co
  skip_cleanup: true
  on:
    tags: true
    repo: bowtie-co/node-utils
  api_key:
    secure: WMbx6rGFYhsilhBa2Lmw4ra7il4EzOEtac7VxTlPZaQDs9NHZK+f3kK9it7I3LzgdgeHhyJHGrq5txUnhNyNhOsOLmWMSGTWly5VwO2L97MXiIZeiPQlXkMdXAj4Ai/xtN7BbgmM56ZIfLhrrUxJm/Gw+xCVz44smbCs3ul14VCSIU0IcvAWz3pCL8CgWyQRyt0wndr7HbjE8/E9aa4rgb0SM/3q0Biqlp3UZeq+9t9gVkgKPPvDtuaqQ8OF3z0NmnjNr/PN9zXVdT60iKisXq4gaREl4JDedNY3OwU+6NVMo55tYwxYFvAXqTjn3m7WvQ0F9+6f4uSSHRhbFjhCjmOyOYWr1+WnvKHP+HL3LfM9IO+Q7d4jk9PnngD1uTzp2WW6S1a8YNhiJ7gD0WfO6+3pJzNz2OSMPX2b/k550zBMEMcSSyEYMSqmpShCpGGFll5/2Tibsr70EijnCLNtRwouiVbmyH2w2ya6dfu6GZvryaHFMpOdlTgegIlYYBRebdMcl1kZ/aaZuOYRoMl7NhSAxhLlzlR2fDk2AHivaF2LjSYTfpBngWn3qgsxe37k5Z+7hqlGpV85JNu/HX4kWSxmMd+OOyUydrHPmtFU2oDvmiKbSAmVFiLV06jJ49y9UCqoNAawpImfZIFAJzo9vjsQgqO9moi5tR16TyXrj0U=
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: VsJFinYX2KkjzwHHS7Y/esOEgeB9MhTrLiLnHby0oLjEsLoW79qk1G0qevWQBy9KpQkjUEImHE1RCUgSWiid/+u9xFZqqnnQKmg4O/124aRfhKGnD5hNFbP4k3Z7jZrQSWj3FhGZpl1pFDUzrMM62dOQAVL0DDDtoBCOoYhMrCNOe9uBltPP70W1SydflW0ZMsGtPbE7+COaYdHBOcpaCjKUOrMHN+nLJVtx4SYVnaBTXpdJTSfMGIUUeFVJxl++LGm1kTZXF+SQPFxLp+yGG1f+N+x1swIokf/Ya8Vm8UJ9hmVdfStE56v5urDbrG/UxTM5kpYZ+KPnYAsrhnrwEDEsK38EoOKGeTu5UcR5vUkrw3eRTr778QWRU2ud+eJaKdpsc98TCg5It4JoFbbnXt5WWXiDiojtN6wK6HIVmOXMOyQvdp4E2kgBqpc0wN+cBKi0aSC4oirDl0w/+6UeXy7qc1yHZnVwRnrK63J3EEzseeTvY+EcPYpaWHpWu7fKDe1iAf9k9YY838/xWgHQVRXVIjepLFs/R8T/tteJ2noD0i9nZ1KRSDGO90cmHMmlnqpVR6pE6do4KbHqmpz4ZatYqrgRMvX/+cgUfrf+Xay4OqKbLCGQ5dih+R6w+HGgp92DUqPK2T70myVJqqSlPsNUznVxAjFa4nXrMtyDdbE=
