language: node_js
node_js:
- 8
before_script:
  - npm run build
deploy:
  provider: npm
  email: charlie@bowtie.co
  on:
    tags: true
    repo: bowtie-co/node-utils
  api_key:
    secure: WMbx6rGFYhsilhBa2Lmw4ra7il4EzOEtac7VxTlPZaQDs9NHZK+f3kK9it7I3LzgdgeHhyJHGrq5txUnhNyNhOsOLmWMSGTWly5VwO2L97MXiIZeiPQlXkMdXAj4Ai/xtN7BbgmM56ZIfLhrrUxJm/Gw+xCVz44smbCs3ul14VCSIU0IcvAWz3pCL8CgWyQRyt0wndr7HbjE8/E9aa4rgb0SM/3q0Biqlp3UZeq+9t9gVkgKPPvDtuaqQ8OF3z0NmnjNr/PN9zXVdT60iKisXq4gaREl4JDedNY3OwU+6NVMo55tYwxYFvAXqTjn3m7WvQ0F9+6f4uSSHRhbFjhCjmOyOYWr1+WnvKHP+HL3LfM9IO+Q7d4jk9PnngD1uTzp2WW6S1a8YNhiJ7gD0WfO6+3pJzNz2OSMPX2b/k550zBMEMcSSyEYMSqmpShCpGGFll5/2Tibsr70EijnCLNtRwouiVbmyH2w2ya6dfu6GZvryaHFMpOdlTgegIlYYBRebdMcl1kZ/aaZuOYRoMl7NhSAxhLlzlR2fDk2AHivaF2LjSYTfpBngWn3qgsxe37k5Z+7hqlGpV85JNu/HX4kWSxmMd+OOyUydrHPmtFU2oDvmiKbSAmVFiLV06jJ49y9UCqoNAawpImfZIFAJzo9vjsQgqO9moi5tR16TyXrj0U=
